FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y python3-venv 

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]